version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../temp_map/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: library/postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=temperature_db
      - POSTGRES_PASSWORD=temperature123
      - POSTGRES_USER=dbuser

volumes:
  postgres_data: