# Generated by Django 3.0.3 on 2020-03-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_dashboard', '0002_auto_20200304_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='fahrenheit',
        ),
    ]
